"""Exercise delayed previews, integrity failures, and clipboard denial locally.

The custom response is generated by the real CAD bridge, then replayed with
controlled delays/failures. These are browser-state checks, not geometry tests.
"""
import hashlib
import json
import os
from pathlib import Path
import sys
import time
import traceback
from urllib.parse import parse_qs, quote, unquote, urlparse

from playwright.sync_api import sync_playwright
from browser_assets import OFFLINE_BASE, attach_assets
from browser_transfers import DEFERRED_BODY
from validation_job import native_request

CLOUD = Path(__file__).resolve().parent
ROOT = CLOUD.parent
OFFLINE = "--offline" in sys.argv
BASE = OFFLINE_BASE if OFFLINE else (sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:5178")
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", str(ROOT.parent / ".cad-cache/browsers"))


def main():
    failures, passed, browser_errors = [], [], []
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True, args=["--use-angle=swiftshader", "--enable-unsafe-swiftshader"])
        context = browser.new_context(viewport={"width": 1440, "height": 1080}, accept_downloads=True)
        context.set_default_timeout(10000)
        if OFFLINE:
            attach_assets(context)
            status, custom_mesh, custom_headers = native_request({"model": "parts_tray", "parameters": {"length": 180}})
            assert status == 200
        else:
            response = context.request.post(BASE + "/api/generate", data={"model": "parts_tray", "parameters": {"length": 180}}, timeout=120000)
            assert response.ok, response.text()
            custom_mesh = response.body()
            custom_headers = {"Content-Type": "model/stl", "X-Model-Metadata": response.headers["x-model-metadata"]}

        def new_page():
            page = context.new_page()
            page.on("pageerror", lambda error: browser_errors.append(str(error)))
            return page

        def catalog(page):
            page.goto(BASE)
            page.wait_for_function("() => document.querySelectorAll('.card').length === 53")

        def open_tray(page):
            page.locator('[data-model="parts_tray"]').click()
            page.wait_for_function("() => !document.querySelector('#download').disabled")

        def pending_route(page, waiting):
            deadline = time.monotonic() + 10
            while not waiting and time.monotonic() < deadline:
                page.wait_for_timeout(50)
            assert waiting, "Expected request was not intercepted"
            return waiting.pop(0)

        def static_integrity():
            page = new_page()
            mesh = bytearray((CLOUD / "public/models/parts_tray.stl").read_bytes())
            mesh[0] ^= 1  # A legal STL header edit still has the wrong catalog hash.
            page.route("**/models/parts_tray.stl", lambda route: route.fulfill(body=bytes(mesh), content_type="model/stl"))
            catalog(page)
            page.locator('[data-model="parts_tray"]').click()
            page.wait_for_function("() => document.querySelector('#preview-loading').hidden")
            assert page.locator("#download").is_disabled(), "Corrupted original mesh was offered for download"
            assert page.locator("#form-message").get_attribute("class").endswith("error")
            page.close()

        def clipboard_denial():
            page = new_page()
            page.add_init_script("Object.defineProperty(navigator, 'clipboard', { value: { writeText: async () => { throw new Error('denied'); } } });")
            catalog(page)
            open_tray(page)
            page.locator('[data-parameter="length"]').fill("180")
            page.locator("#share").click()
            page.wait_for_function("() => document.querySelector('#share-message').textContent.includes('page URL')")
            params = parse_qs(urlparse(page.url).query)
            assert json.loads(params["p"][0])["length"] == 180, "Fallback URL omitted unsaved dimensions"
            page.locator('[data-parameter="length"]').fill("")
            page.locator("#share").click()
            assert "enter a number" in page.locator("#form-message").inner_text()
            assert "error" in page.locator("#form-message").get_attribute("class")
            page.close()

        def original_arrives_after_custom():
            page = new_page()
            page.add_init_script(DEFERRED_BODY + """const originalFetch = window.fetch;
              window.fetch = async (...args) => {
                const response = await originalFetch(...args);
                if (String(args[0]).endsWith('/models/parts_tray.stl')) {
                  const buffer = await response.arrayBuffer();
                  window.deferFileBody(response, buffer, () => new Promise(resolve => {
                    window.releaseOriginal = resolve;
                  }));
                }
                return response;
              };""")
            page.route("**/api/generate", lambda route: route.fulfill(body=custom_mesh, headers=custom_headers))
            catalog(page)
            page.locator('[data-model="parts_tray"]').click()
            page.wait_for_function("() => typeof window.releaseOriginal === 'function'")
            page.locator('[data-parameter="length"]').fill("180")
            page.locator("#rebuild").click()
            page.wait_for_function("() => !document.querySelector('#download').disabled")
            assert page.locator("#model-size").inner_text() == "180 × 100 × 24"
            page.evaluate("window.releaseOriginal()")
            # Drain queued fetch continuations and rendering before checking the UI.
            page.evaluate("() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))")
            assert page.locator("#model-size").inner_text() == "180 × 100 × 24", "Late default overwrote the custom preview"
            assert not page.locator("#download").is_disabled()
            with page.expect_download() as download_event:
                page.locator("#download").click()
            assert hashlib.sha256(Path(download_event.value.path()).read_bytes()).digest() == hashlib.sha256(custom_mesh).digest()
            page.close()

        def switch_during_viewer_load():
            page = new_page()
            waiting = []
            page.route("**/assets/viewer-*.js" if OFFLINE else "**/web/viewer.js*", lambda route: waiting.append(route))
            catalog(page)
            page.locator('[data-model="soap_dish_assembly"]').click()
            # Polling a normal DOM condition also lets Playwright dispatch routes.
            page.wait_for_function("() => document.querySelector('#editor').open")
            viewer_route = pending_route(page, waiting)
            with page.expect_response(lambda response: response.url.endswith("/models/soap_dish_tray.stl")):
                page.locator('[data-part="soap_dish_tray"]').click()
            page.evaluate("() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))")
            viewer_route.fallback()
            page.wait_for_function("() => !document.querySelector('#download').disabled")
            page.wait_for_function("() => document.querySelector('#viewer').getAttribute('aria-busy') === 'false'")
            assert page.locator("#viewer canvas").count() == 1, "Model switch created duplicate viewers"
            assert page.locator("#model-size").inner_text() == "120 × 84 × 14"
            assert page.locator("#mesh-status").inner_text() == "Original dimensions"
            page.close()

        def edits_during_build():
            page = new_page()
            waiting = []
            page.route("**/api/generate", lambda route: waiting.append(route))
            catalog(page)
            open_tray(page)
            for edit in ("190", ""):
                page.locator('[data-parameter="length"]').fill("180")
                page.locator("#rebuild").click()
                page.wait_for_function("() => document.querySelector('#rebuild').disabled")
                route = pending_route(page, waiting)
                page.locator('[data-parameter="length"]').fill(edit)
                route.fulfill(body=custom_mesh, headers=custom_headers)
                page.wait_for_function("() => !document.querySelector('#rebuild').disabled")
                assert page.locator("#download").is_disabled()
                message = page.locator("#form-message").inner_text()
                assert ("Update the preview" in message if edit else "enter a number" in message), message
                assert "ready" not in message.lower() or "edits are ready" in message.lower(), message
            page.close()

        def stale_clipboard_completion():
            page = new_page()
            page.add_init_script("Object.defineProperty(navigator, 'clipboard', { value: { writeText: () => new Promise(resolve => { window.completeClipboard = resolve; }) } });")
            catalog(page)
            open_tray(page)
            page.locator("#share").click()
            page.wait_for_function("() => typeof window.completeClipboard === 'function'")
            page.locator("#close-editor").click()
            page.locator('[data-model="cable_comb"]').click()
            page.wait_for_function("() => !document.querySelector('#download').disabled")
            page.evaluate("window.completeClipboard()")
            assert page.locator("#share-message").is_hidden()
            page.close()

        def custom_integrity():
            page = new_page()
            mesh = bytearray(custom_mesh)
            mesh[0] ^= 1
            page.route("**/api/generate", lambda route: route.fulfill(body=bytes(mesh), headers=custom_headers))
            catalog(page)
            open_tray(page)
            page.locator('[data-parameter="length"]').fill("180")
            page.locator("#rebuild").click()
            page.wait_for_function("() => document.querySelector('#form-message').classList.contains('error')")
            assert page.locator("#model-size").inner_text() == "150 × 100 × 24"
            assert page.locator("#download").is_disabled()
            page.locator('[data-parameter="length"]').fill("150")
            assert not page.locator("#download").is_disabled(), "Previous verified preview was discarded"
            page.close()

        def catalog_image_fallback():
            page = new_page()
            page.add_init_script("""const getContext = HTMLCanvasElement.prototype.getContext;
              HTMLCanvasElement.prototype.getContext = function(type, ...args) {
                return type.startsWith('webgl') ? null : getContext.call(this, type, ...args);
              };""")
            page.route("**/api/generate", lambda route: route.fulfill(body=custom_mesh, headers=custom_headers))
            catalog(page)
            open_tray(page)
            page.locator('[data-parameter="length"]').fill("180")
            page.locator("#rebuild").click()
            page.wait_for_function("() => !document.querySelector('#download').disabled")
            assert page.locator("#model-size").inner_text() == "180 × 100 × 24", page.locator("#model-size").inner_text()
            page.wait_for_function("() => document.querySelector('#viewer').getAttribute('aria-busy') === 'false'")
            assert page.locator("#fallback-image").is_visible(), "Fallback image is hidden"
            assert page.locator("#preview-badge").text_content() == "Original catalog image", page.locator("#preview-badge").text_content()
            assert "original model" in page.locator("#download-note").inner_text(), page.locator("#download-note").inner_text()
            assert page.locator(".view-tools").is_hidden(), "Unavailable 3D controls remain visible"
            page.screenshot(path=str(ROOT / "review/cloud_catalog_image_fallback.png"), full_page=False)
            page.close()

        def mismatched_model_details():
            page = new_page()
            metadata = json.loads(unquote(custom_headers["X-Model-Metadata"]))
            reply_headers = dict(custom_headers)
            page.route("**/api/generate", lambda route: route.fulfill(body=custom_mesh, headers=reply_headers))
            catalog(page)
            open_tray(page)
            cases = [
                metadata | {"model": "cable_comb"},
                metadata | {"units": "inches"},
                metadata | {"parameters": metadata["parameters"] | {"length": 150}},
                metadata | {"bounds_mm": [180, None, 24]},
                None,
            ]
            for details in cases:
                reply_headers["X-Model-Metadata"] = quote(json.dumps(details))
                page.locator('[data-parameter="length"]').fill("180")
                page.locator("#rebuild").click()
                page.wait_for_function("() => !document.querySelector('#rebuild').disabled")
                assert "error" in page.locator("#form-message").get_attribute("class")
                assert "model details" in page.locator("#form-message").inner_text()
                assert page.locator("#download").is_disabled()
                assert page.locator("#model-size").inner_text() == "150 × 100 × 24"
            # Field ordering can differ between Python JSON and browser form inputs.
            details = metadata | {"parameters": dict(reversed(list(metadata["parameters"].items())))}
            reply_headers["X-Model-Metadata"] = quote(json.dumps(details))
            page.locator("#rebuild").click()
            page.wait_for_function("() => !document.querySelector('#download').disabled")
            assert page.locator("#model-size").inner_text() == "180 × 100 × 24"
            page.close()

        for test in (static_integrity, clipboard_denial, original_arrives_after_custom,
                     switch_during_viewer_load, edits_during_build, stale_clipboard_completion,
                     custom_integrity, catalog_image_fallback, mismatched_model_details):
            try:
                test()
                passed.append(test.__name__)
                print(f"PASS {test.__name__}", flush=True)
            except Exception as error:
                details = traceback.format_exc()
                failures.append(dict(test=test.__name__, error=str(error), traceback=details))
                print(f"FAIL {test.__name__}: {details}", flush=True)
        context.close()
        browser.close()
    report = dict(endpoint=BASE, passed=passed, failures=failures, browser_errors=browser_errors,
                  fixture="Real parts_tray CAD build with length=180; responses replayed locally",
                  mesh_sha256=hashlib.sha256(custom_mesh).hexdigest(),
                  transport="compiled assets and native jobs through Playwright routes" if OFFLINE else "local HTTP bridge")
    (ROOT / "review/cloud_ui_state_validation.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    assert not failures and not browser_errors, report


if __name__ == "__main__":
    main()
